[font]
size = 14.0

# deprecated, use this instead:
# defaults -currentHost write -g AppleFontSmoothing -int 0
# use_thin_strokes = true

[font.normal]
family = "SauceCodePro Nerd Font Mono"

[[hints.enabled]]
command = "open"
post_processing = true
regex = "(ipfs:|ipns:|magnet:|mailto:|gemini:|gopher:|https:|http:|news:|file:|git:|ssh:|ftp:)[^\u0000-\u001F\u007F-<>\"\\s{-}\\^⟨⟩`]+"

[hints.enabled.binding]
key = "U"
mods = "Control|Shift"

[hints.enabled.mouse]
enabled = true
mods = "Shift"

[keyboard]
bindings = [
  { key = "Slash", mods = "Control", chars = "\u001F" },
]

[selection]
save_to_clipboard = true
